### PR TITLE
GRAIL - A Music Identity Space API

### PR DESCRIPTION
**Pull request by MDBarone**

### CODE REVIEW

**Comment by ejhumphrey** [comment]
fyi: the authors named in the CC license haven't rendered correctly, I don't think

**Comment by craffel** [comment]
Thanks for the submission!  Sounds like a truly useful service.  I am interested in finding out why only about half of the MSD was matched, but this is something we can discuss at the LBD session :).  Beyond Eric's comment (good catch, thank you!), I noticed a few minor issues:

You don't define the acronym ISRC, this could be helpful.
"types of seced data" -> "types of seed data" (?)
"Furthermore,the quality" -> "Furthermore, the quality"

If you choose to correct these issues, please re-follow steps 6-8 [here](https://github.com/ismir-net/ismir2016-lbd#submission-tutorial) to upload your updated PDF.  Either way, post a comment in this pull request and I'll merge it.  Thanks!

**Comment by MDBarone** [comment]
CC License rendering and typos fixed, thank you!

MSD matching is 50% due to a few factors. IDs in the MSD have not been updated and no longer exist in the APIs. Furthermore, we used additional validation steps which reduced linkage success rate, for a higher degree of accuracy/confidence. Happy to go into more detail at LBD.

**Comment by craffel** [comment]
Merging, thanks!

**Pull request merged**
