### PR TITLE
Böck madmom LBD paper

### PR DESCRIPTION
**Pull request by superbock**

### CODE REVIEW

**Comment by craffel** [comment]
Thanks!  Great that we will have a madmom cite.  Some minor things I noticed on my read-through:

In the sentence "Processors can also be serialised...", Processors is not italicized.
"implements some in MIR commonly used methods" seems like it should be "implements some methods commonly used in MIR"
At the end of a sentence you have "etc.."; the convention is to use a single period, etc.

If you want to make these changes, please just replace your PDF and ping this PR to update me; if not, I will still accept it as-is, just let me know!

**Comment by superbock** [comment]
Thanks for your comments. I will update the paper accordingly and let you know when done.

**Comment by superbock** [comment]
Done, can be merged.

**Comment by craffel** [comment]
Merged, thanks!

**Pull request merged**
