### PR TITLE
JS-XTRACT: A Realtime audio feature extraction library for the web

### PR DESCRIPTION
**Pull request by nickjillings**

### CODE REVIEW

**Comment by craffel** [comment]
Hi, thanks for your submission!  Sounds like a very useful library, it's exciting to get this functionality in the browser, and I appreciate the benchmarks.  A few minor nitpicks: 
- Object-oriented typically has a hyphen.
- You use the acronym HPS but don't define what it is (I assume harmonic peak spectrum).
- Around 'views', looks like you used two single quotes, instead of `views'.
- Alternatively, For should be Alternatively, for 
- Footnotes should go after punctuation, like this.<sup>1</sup>

If you choose to make these edits, please follow steps 6-8 again from [here](https://github.com/ismir-net/ismir2016-lbd) and then ping this thread to let me know.  Thanks!

**Comment by nickjillings** [comment]
Hi, thanks for the proof reading! I've made the changes and submitted a new pull request.

**Comment by nickjillings** [comment]
Please hold for a second! There is a merge conflict my end!

**Comment by nickjillings** [comment]
OK, all ready on 3acb03a86f3421e11d661cdec5aefb773238e90c

**Comment by craffel** [comment]
Thank you!  Merging.

**Pull request merged**
