### PR TITLE
Real-time Audio Interaction in Serious Games for Music Learning

### PR DESCRIPTION
**Pull request by IsabelBarbancho**

### CODE REVIEW

**Comment by craffel** [comment]
Thanks for your submission!  Sorry for the delay in reviewing.  The apps look fun an useful.  

I found a couple of minor typos: 
"the audio engine recognize this seven notes" -> "the audio engine recognizes these seven notes"
"a wider range of notes thatn in previous" -> "a wider range of notes than in previous"
"The game is suited for kids and women voices" -> "The game is suited for kids' and women's voices"
"the game offer the possibility" -> "the game offers the possibility"
I think you also have an extra period after Malaga in the final sentence of your Acknowledgements, but I'm not sure.

I would also suggest you use one of LaTeX's URL packages for your URL, because the URLs in your captions are being corrupted because they are broken across two lines (for example, in Figure 1 the link only leads to https://itunes.apple.com/us/app/singncolour-).  

Once you make these changes, please re-submit (following steps 6 through 8 from https://github.com/ismir-net/ismir2016-lbd#submission-tutorial ) and I will accept it.  Thanks!

**Comment by IsabelBarbancho** [comment]
I have made the changes. Hopefully the URLs in the captions work properly now....

Looking forward to seeing you all in New York!

**Comment by craffel** [comment]
Hey Isabel, looks like the links are still not working.  Are you using a LaTeX url package?

**Comment by craffel** [comment]
Merged in 22014e1ad92f7a8c82df47c47c334933424f5668.  Thanks!

**Pull request closed without merging**
