### PR TITLE
Entropy and the Estimation of Musical Ability

### PR DESCRIPTION
**Pull request by DeadHeadRussell**

### CODE REVIEW

**Comment by craffel** [comment]
Thank you for your submission! It was an interesting read.  The only thing I am confused about is how you compute the entropy of a spectrogram.  The `x` in your Equation (1) is a discrete probability distribution (often a histogram), but a spectrogram is a two-dimensional matrix.  Do you compute a histogram of bin energies over time (seems most likely)?  Do you flatten the spectrogram into one big vector?  This is worth describing.  Once you clarify this, I'm happy to accept the paper.  Also, since you have extra space, it would be cool to put a figure or two in (maybe of some exemplary distributions for highly- and lowly-rated songs), but that's not a requirement.

**Comment by DeadHeadRussell** [comment]
Ah, we weren't clear enough on how we compute and use the spectrogram.  I'll clear that up and toss in a couple of figures and resubmit that either tonight / tomorrow.  Thanks for the feedback!

**Comment by craffel** [comment]
Great - just ping this thread when you've updated the paper so that GitHub notifies me.  Thanks!

**Comment by DeadHeadRussell** [comment]
I've updated the submission both clarifying how we compute the spectrum and adding in two figures.

**Comment by craffel** [comment]
Excellent!  Thank you again!

**Pull request merged**
