### PR TITLE
Towards automatic music recommendation for audio branding scenarios

### PR DESCRIPTION
**Pull request by martinherzog**

### CODE REVIEW

**Comment by craffel** [comment]
Thanks for the submission!  Would be interesting to compare the MBET terms to common music tags from free-form music tagging datasets.  I was also surprised to see gender as an attribute as I don't typically think of music as gendered - will make for interesting discussion.  Merging, see you at ISMIR!

**Comment by martinherzog** [comment]
Thanks. Looking forward to it!

**Comment by martinherzog** [comment]
[herzog-towards.pdf](https://github.com/ismir-net/ismir2016-lbd/files/399990/herzog-towards.pdf)
--> just a small correction within the description of MBET.

**Comment by craffel** [comment]
Hey - if you have a correction, please delete your fork and start over with the new PDF creating a new pull request.  This one's already been merged.  if you need any help with these steps, please let me know!

**Comment by martinherzog** [comment]
Alright, thanks.

**Pull request merged**
