### PR TITLE
Complex-Valued Musical Source Localization

### PR DESCRIPTION
**Pull request by woodshop**

### CODE REVIEW

**Comment by craffel** [comment]
Thanks, this looks great!  I did not find any typos/grammatical errors/etc.  It would be cool to see a comparison to a non-complex NN system, or some other baseline, if available.  Finally, since you do not end up using Equation (2), I think you can omit it.

**Comment by woodshop** [comment]
Both error functions were used (Eq 2 for linear autoencoder, Eq 3 for azimuthal inference). I'll make it more clear that both error functions were used. A comparison to real nets is forthcoming in a few days. Thanks for the feedback!

**Comment by craffel** [comment]
> Both error functions were used (Eq 2 for linear autoencoder, Eq 3 for azimuthal inference).

Ah, got it, sorry, missed that.

> A comparison to real nets is forthcoming in a few days.

Do you want to wait to merge for that?

**Comment by woodshop** [comment]
Yeah, let's wait to merge. It will make do it sooner if we wait :)

**Comment by kylemcdonald** [comment]
just checking this, cool to see some more results andy! :) but also very curious to see the comparison to a real valued network.

**Comment by craffel** [comment]
What's the verdict, @woodshop ?  You wanna present this?

**Pull request closed without merging**
